### ISSUE TITLE
Crashes when Oclockvita is enabled

### ISSUE THREAD

**Issue by EmiyaBestBoy** [Electry/VitaGrafix#126]
When I enable Oclockvita by using molecular shell and refreshing the config.txt opening a game that uses VitaGrafix crashes, the only one I’ve tested is World of Final Fantasy.

**Comment by gensosuikoden** [comment]
You could try one of the other Overclock plugins such as Ultimate VSH or Loli-Con Overclo. Alternatively, if you want to stick with OclockVita you could try the old vita plugins manager app provided your config.txt is on ux0 and not ur0. I don't have my Vita to hand at the moment but I think it's this one and I can confirm that it does work for Oclock Vita.

http://vitadb.rinnegatamante.it/#/info/152

So how would it benefit you / prevent your crashing problem? Well, rather than automating editing of the config.txt and requiring a reload of the config.txt each time you change, what it does is create separate folders for compatible plugins and disabled plugins and swaps the .suprx file(s) of the plugin(s) back and forth between them. So you have your config.txt set up to include the plugins in question and then you just use the app to enable or disable. The config.txt stays the same, as though the plugin is activated but whether or not the plugin's suprx that is referred in the config.txt is available or, to put it another way, in the correct location for it to work, depends on whether or not you have enabled it in the app.

There are other more modern plugin managers that have better compatibility with all plugins but bear in mind that all of those require a config.txt reload after each change and, if it is a kernel plug-in, then a reboot too. The app I am referring to is old and no longer maintained but just for your particular use case and issues with Oclock Vita then it should suffice.
