### ISSUE TITLE
PCSF00243 won't apply patch in any way

### ISSUE THREAD

**Issue by EnekoT2001** [Electry/VitaGrafix#142]
Hi, I'm trying to apply 60fps/native res. to Killzone: mercenary (Eur) and I can't, I tried like months ago (when worked badly) and I could, but now no matter how and what I configure, it'll say me that "Failed to open config file, do you have ioPlus installed?" Every time, even when I disable it. With other games works fine (like GoF collection, RE Revelations 2...

I reinstalled everything, deleted the config file, tried to do it with the vitagrafix configurator... I even tried to put in the config.txt just the config for this only game or deleting the txt, and it doesn't work. I have ioPlus installed correctly, idk what is happening.

**Comment by justalex95** [comment]
The only thing I can think of is that killzone isnt updated to the latest patch. I'm using the eur version without any problems w/60fps limit @ 960x544, make sure you download both updates

**Comment by teamjin** [comment]
1. There are a few issues here but I will start with the main one; you have not installed VitaGrafix correctly. If you install VitaGrafix and it brings up a prompt regarding ioPlus, it is because the module for ioPlus is not interacting as expected so VitaGrafix will not work. It probably means you have a faulty config file or your VitaGrafix/ioPlus is corrupt.
2. Open notepad and paste my config settings here #153 (4th post), see if it works. Redownload ioPlus and VitaGrafix. I tested PCSF00243 and had no issue.  
3. You may have conflicting plug-ins effecting PCSF00243 whilst still allowing other games to work normally but I suggest you start from my config posted in point 2. Don't alter it in any way until after you have tested it (with the exception of replacing `ux0:tai/` with `ur0:tai/` if you use sd2vita).
4. PCSF00243 uses dynamic resolution by default (I am not clear on what that is) and apparently you can't get 60fps. You can still configure using VitaGrafix but I assume it doesn't do much good or make much difference to the defaults. 
5. The current README.md does not actually display this but VitaGrafix defaults for PCSF00243 are both set to OFF. So when you load it, it will say `PCSF00243: disabled` you will have to change it manually. Refer to the old README.md https://github.com/Electry/VitaGrafix/tree/v2.2

**Comment by EnekoT2001** [comment]
> 1. There are a few issues here but I will start with the main one; you have not installed VitaGrafix correctly. If you install VitaGrafix and it brings up a prompt regarding ioPlus, it is because the module for ioPlus is not interacting as expected so VitaGrafix will not work. It probably means you have a faulty config file or your VitaGrafix/ioPlus is corrupt.
> 2. Open notepad and paste my config settings here #153 (4th post), see if it works. Redownload ioPlus and VitaGrafix. I tested PCSF00243 and had no issue.
> 3. You may have conflicting plug-ins effecting PCSF00243 whilst still allowing other games to work normally but I suggest you start from my config posted in point 2. Don't alter it in any way until after you have tested it (with the exception of replacing `ux0:tai/` with `ur0:tai/` if you use sd2vita).
> 4. PCSF00243 uses dynamic resolution by default (I am not clear on what that is) and apparently you can't get 60fps. You can still configure using VitaGrafix but I assume it doesn't do much good or make much difference to the defaults.
> 5. The current README.md does not actually display this but VitaGrafix defaults for PCSF00243 are both set to OFF. So when you load it, it will say `PCSF00243: disabled` you will have to change it manually. Refer to the old README.md https://github.com/Electry/VitaGrafix/tree/v2.2

Thanks, I'll try this :D

**Comment by EnekoT2001** [comment]
Okay, I updated vitagrafix to the alpha version, and now works just fine, I also did what @teamjin said, moved ioplus to ur0 (i have sd2vita) and changed the config.txt dir for ioplus. And works great, with native resolution and 60FPS, thanks :D
