### ISSUE TITLE
Ioplus is not installed!

### ISSUE THREAD

**Issue by IiovePSV** [Electry/VitaGrafix#153]
I installed the ioplus plug-in correctly, but when I opened the game, I prompted me that I did not install ioplus, which bothered me very much. When I used Vita Grafix 2.5, I had no problem using kuio! Asking for help

**Comment by Babbosh** [comment]
Well, I have installed ioplus correctly too, but unlike yours, it works wonderfully. Maybe your Vita has different antibodies that actually reject Ioplus. Go in the hospital and have your Vita checked up, probably a vaccine is needed.

**Comment by InitialXKO** [comment]
How do you know you did install it correctly? This should not be discussed here.

**Comment by teamjin** [comment]
I am doubting you actually installed ipplus plug-in correctly. The only other thing I can think of is conflicting plug-ins but then again my knowledge of vita coding and software is practically none so there may be other variables to consider.

In any case here is my config that works so you can try that:
```
# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
ux0:tai/ioplus.skprx 
ux0:tai/repatch_4.skprx
# henkaku.skprx is hard-coded to load and is not listed here
ux0:tai/nonpdrm.skprx
*main
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
*
ux0:tai/oclockvita.suprx
*ALL
ux0:tai/VitaGrafix.suprx
```

> How do you know you did install it correctly? This should not be discussed here.

If the ioplus plugin does not get installed properly, instead of getting the patched message on game startup, VitaGrafix instead gives off an error message relating to ioplus.

**Comment by CmdBlk** [comment]
I’m having the same issue with VitaGrafix 3.2. :/ I’ve uninstalled and reinstalled all plugins related to the tweak and still no luck.

**Comment by Babbosh** [comment]
So if you all allegedly "installed it correctly", what do you really need from us? If you have the arrogance to assume you did nothing wrong, then for sure you need more than a saint to help you all. 
Reinstall it again, in the text use the same exact letters you renamed the plugin with, yes I had trouble with capital letters once, so it is caps sensitive.
More than this I cannot do.

**Comment by teamjin** [comment]
> I’m having the same issue with VitaGrafix 3.2

If you mean VitaGrafix is installed correctly but it gives an error message about ioplus then yes, that is the same issue.

> I’ve uninstalled and reinstalled all plugins related to the tweak and still no luck.

The only way (that I know of) to uninstall plugins in henkaku is to simply remove them from the config.txt file. There technically won't be a way of "reinstalling", only adding and removing what get's loaded up (installed) when Henkaku boots. 

The reason why we would call VitaGrafix a Henkaku plug-in is because it is designed for Henkaku to run it (not the other way round) and as you already know, Henkaku is designed to run on the Vita. Henkaku uses the config file to check what needs to run once you boot your vita. So based on that logic, we can assume that Henkaku on your vita is not able to run the plug-in either because you did not put the files in the right folder (tai folder) or your config.txt file is faulty.

So if VitaGrafix is not working, you basically didn't install it properly. I suggest you open a brand new text document on notepad then paste and save the settings I posted earlier and save it as config.txt. Then remove your old config.txt from your vita (save it for later if you still need it) and use my 1. You will need both ioplus.skprx and VitaGrafix.suprx to be in the tai folder. Test it and see if it works (Don't forget to reboot your vita).

**Comment by justalex95** [comment]
1. if your using sd2vita make sure your plugins are in ur0:tai
2. make sure to disable the kuio plugin if using ioplus (they have the same function as far as I can tell) insert a # at the start of the line of the plugin you want to disable
3. try changing the order of plugins in your config. I use sd2vita and have alot enabled, here's the order of my kernel plugins under kernel: henkaku/gamesd/lolicon/ioplus/vitabright/nonpdrm/repatch/adrenaline

Everything works perfectly, if your using sd2vita always put your plugins in ur0:tai, and delete ux0:tai once you've copied it to ur0

hope it works
