### ISSUE TITLE
Trails of Cold Steel Improper Blur Scailing At Native Res

### ISSUE THREAD

**Issue by mcallbosco** [Electry/VitaGrafix#156]
I have not tested it with TOCS 2 as I want to avoid spoilers but playing TOCS 1 the blur is improperly scaled. I have an example screenshot.
![2018-11-07-201455](https://user-images.githubusercontent.com/26465212/49763406-83ba7c00-fc9a-11e8-8b33-5a980f36acf4.jpg)

![2018-11-07-202323](https://user-images.githubusercontent.com/26465212/49763460-b3698400-fc9a-11e8-9cd8-cdae7cf0fbd0.jpg)

**Comment by mcallbosco** [comment]
As you can see the blur is off centered or something of the like. (You can see it quite good looking at his hair in the first image.)

**Comment by Electry** [comment]
Hey, thanks for reporting.

Yeah, you are right, the blur is off-centered. It can also be seen during the opening cut-scene.
Looks like the game uses slightly higher res. for the blur, 736x408 instead of 720x408, and we're setting both of these values to 960x544 so it doesn't fit properly.

This can be fixed by multiplying the blur width by 1.02222. So, we should use 981x544 blur for 960x544 image.

I presume TOCS 2 is the same as the patch is very similar.

I'll fix this.
If you absolutely can't wait, grab vitasdk, change https://github.com/Electry/VitaGrafix/blob/master/patch.c#L1010 this line to
`vgMakeThumb2_T2_MOV(2, 1, g_main.config.ib[0].width * 1.02222, movs_r2_w_r3_h);`
and recompile the plugin.
