### ISSUE TITLE
[PCSB00877] LEGO Star Wars: The Force Awakens - GPU Driver Crash detected

### ISSUE THREAD

**Issue by ChiSys** [Electry/VitaGrafix#17]
I'm getting with various resolutions a gpu driver crash. A message appears and I have to hard reset (holding power button for 20 sec) and restart the system.

**Comment by Electry** [comment]
Yep, I think 720x408 works, but yeah, the game crashes the vita at native res when opening pause menu (and possibly on other occasions). I will add this to the README.md and make 408p default res for that game.

**Comment by Electry** [comment]
I took a look at this again, and it seems to be VRAM related.

The game allocates two 2 MB mem blocks in VRAM when opening pause menu. After shaving off 6 MB from SceGxmInitializeParams.parameterBufferSize (so that there is more VRAM for the game to use) it no longer crashes at 960x544.

This is the same hacky thing I did to get Ratchet & Clank running at 960x544.

I'll include patch for this in the next preview build, so more people can test it.
