### ISSUE TITLE
[REQUEST] Project Diva F2nd and X 60 FPS

### ISSUE THREAD

**Issue by spanaren** [Electry/VitaGrafix#60]
Your patch for Project Diva F is absolutely fantastic. It is so fantastic that going back to 30 FPS when playing F2nd or X is straight up jarring.

Please patch those two as well so we can play all of Project Diva on Vita in glorious 60 FPS.

**Comment by Electry** [comment]
I thought the framerate was dropping under 60 constantly.

**Comment by spanaren** [comment]
The first few songs I played it was near perfect with only ~2-3 drops for a second or so. After playing with it a bit more, yeah, a bunch of other songs have more frequent drops, which is a shame. It feels amazing to play with it when it works, but the drops do make some sections incredibly frustrating. 

It's up to you in the end, but thanks for the work regardless. I really appreciate the plugin. You're a boss! :)

**Comment by Electry** [comment]
F 2nd and X run at 720x408, so I imagine it would drop even more often (F runs at 640x352), but since F2nd patch is very similar to F, I added it.

Until it is added to proper release, you can try/test the build I posted here: #66 
It has IB and FPS patches for F + F2nd, and IB patch for X.

You could try running it at something like 480x272 for more stable-ish 60 :P but not sure if it's worth it

**Comment by gittyno1** [comment]
In my opinion, 60fps is more important than resolution, as long as resolution as somewhat decent.

**Comment by Antox52** [comment]
to have 60 fps fixed just use the "LOLIcon" plugin, it works very well
