### ISSUE TITLE
Killzone Mercenary

### ISSUE THREAD

**Issue by wbb1977** [Electry/VitaGrafix#66]
Hi,

thanks for this great work. I installed everything and tried Killzone Mercenary. How to get past the title screen "Press Start to continue" when FPS=60 is enabled? I am confused. It is noted in the README that no input works if fps > 59 in game. So I wonder how to get past the title screen? I use it on the PSTV so maybe it is no issue on a normal Vita with touch controls? Killzone is patched to work with controller on PSTV, simulated touch inputs are ignored.

Thx.

-wbb

**Comment by Electry** [comment]
Yep, Vita uses touch controls for menus and regular input stops working at >=60 due to the way it is handled in the game.

Could you try this?
[VitaGrafix_ae2c166.zip](https://github.com/Electry/VitaGrafix/files/2334938/VitaGrafix_ae2c166.zip)

I patched sceCtrlReadBufferPositive calls with sceCtrlPeekBufferPositive which seems to fix the issue on regular Vita.
