### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by molecopopo** [Electry/VitaGrafix#88]

**Comment by Electry** [comment]
this isn't magic

**Comment by Babbosh** [comment]
Oh God lord. Just by reading these kind of silly observations a person can lose around 60% of its IQ points.

**Comment by gittyno1** [comment]
You two can at least be decent enoug and explain to guy in short points instead of being smartasses and saying "it isnt magic" or "you lose IQ by reading"

I am really sorry, but i cant stand the arrogance sometimes. I got nothing against you two, but i needed to say this and you take it as you please.

Ok that was offtopic a bit...

@molecopopo As i understod, god of war and other games that are "hackable" to run at 60fps more or less, they have code inside of them that @Electry finds and messes with it (changing values so that game fps is unlocked). Also as i understood, not all games have that code in them  or run into glitches because they wherent meant to run 60fps. but god of war is a port and originally it runs 60fps on PS2, so its just locked at 30 for vita with that code that Electry finds and unlocks.

Not all games have that or run into problems...thats why he say its not a magic because its not.
I would also like resident evil 2 to run smooth tbh !!

**Comment by Electry** [comment]
I honestly didn't mean to sound arrogant. It's just that it's not really as simple as "trying the same method".
Each game is different.

I am not a game dev and I have very limited understanding of what's going on behind the scenes. If the game doesn't play nice (e.g. 2x speed at 60, glitches, crashes, etc...), there is not much I can do.

**Comment by Babbosh** [comment]
Gittyno1 you don't need to explain anything. People like you have a specific term: SJW. 
The point here is to respect someonelse's work by avoiding superficial and pretentious demands.  This especially if someone does it for free and for the greater good of the Vita community.
No offence taken, don't care if given. World is tough, deal with it.

**Comment by molecopopo** [comment]
Sorry but I did not mean to offend anyone, it was just a question ... thanks gittyno1

**Comment by molecopopo** [comment]
Okay, I'm sorry, okay? I really did not mean to offend from the bottom of my heart, if you do not believe it's your problem.
I'm very happy for the work of the electry and I'm even planning to make a donation, how would I want to offend such a guy?

**Comment by gittyno1** [comment]
@molecopopo  Please dont hide your answer, its not stupid, dont listen to others, let it be, you just did not understand thats normal. Everione is a noob (newbie) in the begining and ask questions that are "stupid".

You really don't deserve to be mocked because of that.

**Comment by Babbosh** [comment]
Close this non issue, please. Otherwise the remaining points of my once fair IQ will totally disappear, along with the ability to write and read.
